const mongoose = require('mongoose');
require('dotenv').config();
const Product = require('./models/Product');

const products = [
  // Electronics (25)
  { title: "Apple MacBook Air M3 (2024)", brand: "Apple", category: "Electronics", price: 1099, originalPrice: 1199, stock: 45, rating: 4.9, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=800", description: "Supercharged by M3, the MacBook Air is incredibly thin, light, and features up to 18 hours of battery life." },
  { title: "Dell XPS 15", brand: "Dell", category: "Electronics", price: 1499, originalPrice: 1699, stock: 32, rating: 4.7, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&q=80&w=800", description: "Immersive 15.6-inch OLED display, Intel Core i7 processor, and NVIDIA RTX graphics." },
  { title: "Samsung Galaxy S24 Ultra", brand: "Samsung", category: "Electronics", price: 1299, originalPrice: 1399, stock: 60, rating: 4.8, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&q=80&w=800", description: "The ultimate smartphone experience with Galaxy AI, Titanium exterior, and incredible camera." },
  { title: "Sony WH-1000XM5", brand: "Sony", category: "Electronics", price: 348, originalPrice: 399, stock: 85, rating: 4.8, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&q=80&w=800", description: "Industry-leading noise cancellation, exceptional sound quality, and all-day comfort." },
  { title: "Apple AirPods Pro (2nd Gen)", brand: "Apple", category: "Electronics", price: 249, originalPrice: 249, stock: 120, rating: 4.9, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&q=80&w=800", description: "Rich, high-quality audio and voice, active noise cancellation, and a customizable fit." },
  { title: "LG C3 65-inch OLED TV", brand: "LG", category: "Electronics", price: 1599, originalPrice: 1999, stock: 15, rating: 4.9, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&q=80&w=800", description: "Self-lit OLED pixels for infinite contrast, perfect black, and over a billion colors." },
  { title: "iPad Pro 12.9 (M2)", brand: "Apple", category: "Electronics", price: 1099, originalPrice: 1199, stock: 40, rating: 4.8, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&q=80&w=800", description: "The ultimate iPad experience with the most advanced display and blazing-fast M2 chip." },
  { title: "Nintendo Switch OLED", brand: "Nintendo", category: "Electronics", price: 349, originalPrice: 349, stock: 95, rating: 4.8, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1617265439401-209935560126?auto=format&fit=crop&q=80&w=800", description: "Play at home or on the go with a vibrant 7-inch OLED screen." },
  { title: "PlayStation 5 Console", brand: "Sony", category: "Electronics", price: 499, originalPrice: 499, stock: 25, rating: 4.9, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&q=80&w=800", description: "Lightning-fast loading with an ultra-high-speed SSD, deeper immersion, and amazing games." },
  { title: "Xbox Series X", brand: "Microsoft", category: "Electronics", price: 499, originalPrice: 499, stock: 30, rating: 4.8, featured: false, bestseller: false, image: "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?auto=format&fit=crop&q=80&w=800", description: "The fastest, most powerful Xbox ever. Play thousands of titles from four generations of consoles." },
  { title: "Bose QuietComfort 45", brand: "Bose", category: "Electronics", price: 329, originalPrice: 329, stock: 50, rating: 4.7, featured: false, bestseller: false, image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&q=80&w=800", description: "Iconic quiet, comfort, and sound. Acoustic Noise Cancelling headphones." },
  { title: "GoPro HERO12 Black", brand: "GoPro", category: "Electronics", price: 399, originalPrice: 399, stock: 65, rating: 4.7, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1564466809058-bf4114d55352?auto=format&fit=crop&q=80&w=800", description: "Incredible image quality, even better HyperSmooth video stabilization, and a huge boost in battery life." },
  { title: "DJI Mini 4 Pro", brand: "DJI", category: "Electronics", price: 759, originalPrice: 759, stock: 20, rating: 4.8, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1579822606859-e9bd117eb8ba?auto=format&fit=crop&q=80&w=800", description: "Mini 4 Pro is DJI's most advanced mini-camera drone to date. It integrates powerful imaging capabilities." },
  { title: "Google Pixel 8 Pro", brand: "Google", category: "Electronics", price: 999, originalPrice: 999, stock: 45, rating: 4.7, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1598327105666-5b89351cb31b?auto=format&fit=crop&q=80&w=800", description: "The all-pro Google phone. Powerful performance, exceptional cameras, and all-day battery." },
  { title: "Amazon Echo Dot (5th Gen)", brand: "Amazon", category: "Electronics", price: 49, originalPrice: 49, stock: 200, rating: 4.6, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1543512214-318c7553f230?auto=format&fit=crop&q=80&w=800", description: "Our best sounding Echo Dot yet. Enjoy an improved audio experience for clearer vocals." },
  { title: "Apple Watch Series 9", brand: "Apple", category: "Electronics", price: 399, originalPrice: 399, stock: 75, rating: 4.8, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&q=80&w=800", description: "Smarter. Brighter. Mightier. With the powerful S9 chip, a superbright display, and magical new ways to interact." },
  { title: "Logitech MX Master 3S", brand: "Logitech", category: "Electronics", price: 99, originalPrice: 99, stock: 85, rating: 4.9, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800", description: "The iconic mouse, now upgraded. Feel every moment of your workflow with even more precision." },
  { title: "Keychron Q1 Pro", brand: "Keychron", category: "Electronics", price: 199, originalPrice: 199, stock: 35, rating: 4.8, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&q=80&w=800", description: "A full metal QMK/VIA wireless custom mechanical keyboard." },
  { title: "Samsung 990 PRO 2TB", brand: "Samsung", category: "Electronics", price: 169, originalPrice: 199, stock: 110, rating: 4.9, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&q=80&w=800", description: "Blistering speed, endless victory. PCIe 4.0 NVMe SSD for gaming and high-performance computing." },
  { title: "Kindle Paperwhite", brand: "Amazon", category: "Electronics", price: 139, originalPrice: 139, stock: 150, rating: 4.8, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800", description: "Now with a 6.8\" display and thinner borders, adjustable warm light, and up to 10 weeks of battery life." },
  { title: "Asus ROG Zephyrus G14", brand: "Asus", category: "Electronics", price: 1399, originalPrice: 1499, stock: 25, rating: 4.7, featured: false, bestseller: false, image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&q=80&w=800", description: "Incredible gaming performance in an ultraportable 14-inch form factor." },
  { title: "Nikon Z6 II Mirrorless Camera", brand: "Nikon", category: "Electronics", price: 1999, originalPrice: 1999, stock: 12, rating: 4.8, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=800", description: "A versatile full-frame mirrorless camera for photos and video." },
  { title: "Sonos Arc Soundbar", brand: "Sonos", category: "Electronics", price: 899, originalPrice: 899, stock: 22, rating: 4.8, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1542728928-1413d1894ed1?auto=format&fit=crop&q=80&w=800", description: "Bring all your entertainment to life with the brilliantly realistic sound of Arc." },
  { title: "Anker PowerCore 26800", brand: "Anker", category: "Electronics", price: 65, originalPrice: 65, stock: 200, rating: 4.7, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&q=80&w=800", description: "Massive capacity portable charger with dual input port and double-speed recharging." },
  { title: "Garmin Fenix 7X Pro", brand: "Garmin", category: "Electronics", price: 899, originalPrice: 899, stock: 18, rating: 4.9, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800", description: "Ultimate multisport GPS smartwatch with solar charging." },

  // Fashion (25)
  { title: "Levi's 501 Original Fit Jeans", brand: "Levi's", category: "Fashion", price: 79, originalPrice: 79, stock: 150, rating: 4.7, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&q=80&w=800", description: "The original blue jean since 1873. A classic straight fit." },
  { title: "Nike Air Max 270", brand: "Nike", category: "Fashion", price: 160, originalPrice: 160, stock: 85, rating: 4.8, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800", description: "Nike's first lifestyle Air Max brings you style, comfort and big attitude." },
  { title: "Adidas Ultraboost Light", brand: "Adidas", category: "Fashion", price: 190, originalPrice: 190, stock: 95, rating: 4.8, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1518002171953-a080ee817e1f?auto=format&fit=crop&q=80&w=800", description: "Experience epic energy with the new Ultraboost Light, our lightest Ultraboost ever." },
  { title: "Tommy Hilfiger Classic Polo", brand: "Tommy Hilfiger", category: "Fashion", price: 65, originalPrice: 65, stock: 110, rating: 4.6, featured: false, bestseller: false, image: "https://images.unsplash.com/photo-1596755094514-f87e32f85e23?auto=format&fit=crop&q=80&w=800", description: "A classic cotton polo shirt featuring the iconic flag logo on the chest." },
  { title: "The North Face Nuptse Jacket", brand: "The North Face", category: "Fashion", price: 330, originalPrice: 330, stock: 40, rating: 4.9, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&q=80&w=800", description: "An iconic, boxy, water-repellent jacket insulated with 700-fill down." },
  { title: "Ray-Ban Classic Aviator", brand: "Ray-Ban", category: "Fashion", price: 163, originalPrice: 163, stock: 120, rating: 4.8, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&q=80&w=800", description: "Currently one of the most iconic sunglass models in the world." },
  { title: "Calvin Klein Boxer Briefs (3-Pack)", brand: "Calvin Klein", category: "Fashion", price: 45, originalPrice: 45, stock: 200, rating: 4.7, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&q=80&w=800", description: "Classic Calvin Klein logo waistband and comfortable cotton stretch fabric." },
  { title: "Carhartt WIP Chase Sweatshirt", brand: "Carhartt", category: "Fashion", price: 88, originalPrice: 88, stock: 65, rating: 4.7, featured: false, bestseller: false, image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800", description: "A heavy-weight, brushed cotton blend sweatshirt featuring a subtle logo embroidery." },
  { title: "Converse Chuck Taylor All Star", brand: "Converse", category: "Fashion", price: 65, originalPrice: 65, stock: 180, rating: 4.8, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800", description: "The iconic high top canvas sneaker with the classic star ankle patch." },
  { title: "Patagonia Better Sweater", brand: "Patagonia", category: "Fashion", price: 149, originalPrice: 149, stock: 70, rating: 4.8, featured: false, bestseller: false, image: "https://images.unsplash.com/photo-1548883354-94cb06a422cc?auto=format&fit=crop&q=80&w=800", description: "A warm, 100% recycled polyester quarter-zip jacket." },
  { title: "Dr. Martens 1460 Smooth Leather Boot", brand: "Dr. Martens", category: "Fashion", price: 170, originalPrice: 170, stock: 55, rating: 4.7, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1605348532760-6753d2c43329?auto=format&fit=crop&q=80&w=800", description: "The original Dr. Martens 8-eye boot. Built with smooth leather and the classic air-cushioned sole." },
  { title: "Ralph Lauren Oxford Shirt", brand: "Ralph Lauren", category: "Fashion", price: 115, originalPrice: 115, stock: 90, rating: 4.6, featured: false, bestseller: false, image: "https://images.unsplash.com/photo-1596755094514-f87e32f85e23?auto=format&fit=crop&q=80&w=800", description: "An iconic piece of American style, this Oxford shirt is a wardrobe staple." },
  { title: "Vans Old Skool", brand: "Vans", category: "Fashion", price: 70, originalPrice: 70, stock: 140, rating: 4.8, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&q=80&w=800", description: "The classic skate shoe that brought the iconic side stripe into the world." },
  { title: "Gucci GG Marmont Belt", brand: "Gucci", category: "Fashion", price: 490, originalPrice: 490, stock: 25, rating: 4.9, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&q=80&w=800", description: "Signature Double G buckle on smooth black leather." },
  { title: "Lululemon Align High-Rise Pant", brand: "Lululemon", category: "Fashion", price: 98, originalPrice: 98, stock: 110, rating: 4.9, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1550246140-5119ae4790b8?auto=format&fit=crop&q=80&w=800", description: "Buttery-soft, weightless Nulu fabric for the ultimate comfort during yoga or lounging." },
  { title: "H&M Oversized T-shirt", brand: "H&M", category: "Fashion", price: 14, originalPrice: 14, stock: 300, rating: 4.4, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=800", description: "A comfortable, everyday oversized cotton tee." },
  { title: "Zara Tailored Blazer", brand: "Zara", category: "Fashion", price: 89, originalPrice: 89, stock: 60, rating: 4.5, featured: false, bestseller: false, image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&q=80&w=800", description: "A sleek tailored blazer for office wear or an elegant night out." },
  { title: "New Balance 550", brand: "New Balance", category: "Fashion", price: 110, originalPrice: 110, stock: 45, rating: 4.8, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800", description: "A classic retro basketball shoe making a huge comeback." },
  { title: "Burberry Classic Trench Coat", brand: "Burberry", category: "Fashion", price: 2490, originalPrice: 2490, stock: 10, rating: 4.9, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&q=80&w=800", description: "The iconic trench coat crafted in England from cotton gabardine." },
  { title: "Casio G-Shock Classic", brand: "Casio", category: "Fashion", price: 99, originalPrice: 99, stock: 150, rating: 4.8, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&q=80&w=800", description: "The rugged, durable classic that started it all." },
  { title: "Rolex Submariner Date", brand: "Rolex", category: "Fashion", price: 10250, originalPrice: 10250, stock: 3, rating: 5.0, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&q=80&w=800", description: "The archetype of the diver's watch. Classic and timeless." },
  { title: "Common Projects Achilles Low", brand: "Common Projects", category: "Fashion", price: 425, originalPrice: 425, stock: 35, rating: 4.8, featured: false, bestseller: false, image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=800", description: "The definitive luxury minimal white sneaker." },
  { title: "Arcteryx Beta LT Jacket", brand: "Arcteryx", category: "Fashion", price: 450, originalPrice: 450, stock: 40, rating: 4.9, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1544642899-f0d6e5f6ed6f?auto=format&fit=crop&q=80&w=800", description: "Lightweight, highly versatile Gore-Tex shell for a range of mountain activities." },
  { title: "Birkenstock Arizona Soft Footbed", brand: "Birkenstock", category: "Fashion", price: 140, originalPrice: 140, stock: 95, rating: 4.7, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&q=80&w=800", description: "The iconic two-strap sandal, now with an extra layer of foam cushioning." },
  { title: "Fjallraven Kanken Backpack", brand: "Fjallraven", category: "Fashion", price: 90, originalPrice: 90, stock: 120, rating: 4.8, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800", description: "Classic everyday backpack made with durable Vinylon F fabric." },

  // Home & Living (20)
  { title: "IKEA Modern Coffee Table", brand: "IKEA", category: "Home & Living", price: 129, originalPrice: 129, stock: 65, rating: 4.5, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?auto=format&fit=crop&q=80&w=800", description: "Minimalist Scandinavian design coffee table with durable finish." },
  { title: "Philips Hue White and Color Smart Bulb", brand: "Philips", category: "Home & Living", price: 45, originalPrice: 49, stock: 150, rating: 4.7, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&q=80&w=800", description: "Add color to any room with millions of shades and smart control." },
  { title: "Dyson V15 Detect Vacuum", brand: "Dyson", category: "Home & Living", price: 749, originalPrice: 749, stock: 35, rating: 4.8, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=800", description: "Dyson's most powerful, intelligent cordless vacuum with laser dust detection." },
  { title: "Le Creuset Dutch Oven 5.5 qt", brand: "Le Creuset", category: "Home & Living", price: 420, originalPrice: 420, stock: 25, rating: 4.9, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1584990347449-a6e558f000fd?auto=format&fit=crop&q=80&w=800", description: "The iconic enameled cast iron Dutch oven that lasts for generations." },
  { title: "Nespresso VertuoPlus", brand: "Nespresso", category: "Home & Living", price: 199, originalPrice: 199, stock: 60, rating: 4.7, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&q=80&w=800", description: "Brews both espresso and regular coffee with Centrifusion technology." },
  { title: "Breville Barista Express", brand: "Breville", category: "Home & Living", price: 749, originalPrice: 749, stock: 20, rating: 4.8, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1587734195503-904fca47e0e9?auto=format&fit=crop&q=80&w=800", description: "Create third wave specialty coffee at home from bean to espresso in less than a minute." },
  { title: "Vitamix 5200 Blender", brand: "Vitamix", category: "Home & Living", price: 499, originalPrice: 499, stock: 40, rating: 4.9, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1585238342024-78d387f4a707?auto=format&fit=crop&q=80&w=800", description: "Professional-grade blender for everything from hot soups to frozen desserts." },
  { title: "Brooklinen Luxe Core Sheet Set", brand: "Brooklinen", category: "Home & Living", price: 179, originalPrice: 179, stock: 85, rating: 4.8, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800", description: "Buttery-smooth 480-thread count sateen sheets." },
  { title: "Herman Miller Aeron Chair", brand: "Herman Miller", category: "Home & Living", price: 1250, originalPrice: 1250, stock: 15, rating: 4.9, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?auto=format&fit=crop&q=80&w=800", description: "The gold standard in ergonomic office seating." },
  { title: "Yeti Rambler 20 oz Tumbler", brand: "Yeti", category: "Home & Living", price: 35, originalPrice: 35, stock: 200, rating: 4.9, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1614777986387-015c2a89b696?auto=format&fit=crop&q=80&w=800", description: "Double-wall vacuum insulation keeps drinks hot or cold for hours." },
  { title: "iRobot Roomba j7+", brand: "iRobot", category: "Home & Living", price: 799, originalPrice: 799, stock: 30, rating: 4.6, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1589004558550-937b420076a5?auto=format&fit=crop&q=80&w=800", description: "Self-emptying robot vacuum that avoids pet waste and cords." },
  { title: "Zinus 12 Inch Green Tea Memory Foam Mattress", brand: "Zinus", category: "Home & Living", price: 299, originalPrice: 349, stock: 50, rating: 4.5, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1505693314120-0d443867891c?auto=format&fit=crop&q=80&w=800", description: "Pressure-relieving memory foam infused with green tea for freshness." },
  { title: "Cuisinart 14-Cup Food Processor", brand: "Cuisinart", category: "Home & Living", price: 249, originalPrice: 249, stock: 45, rating: 4.8, featured: false, bestseller: false, image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&q=80&w=800", description: "A workhorse in the kitchen. Chops, slices, shreds, and purées." },
  { title: "Nest Learning Thermostat", brand: "Google", category: "Home & Living", price: 249, originalPrice: 249, stock: 75, rating: 4.7, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1567925072551-f70366ebff2a?auto=format&fit=crop&q=80&w=800", description: "Programs itself and pays for itself. Save energy effortlessly." },
  { title: "Staub Cast Iron Cocotte", brand: "Staub", category: "Home & Living", price: 350, originalPrice: 350, stock: 25, rating: 4.9, featured: false, bestseller: false, image: "https://images.unsplash.com/photo-1584990347449-a6e558f000fd?auto=format&fit=crop&q=80&w=800", description: "French enameled cast iron, exceptional for slow-cooking meats and vegetables." },
  { title: "Fellow Stagg EKG Electric Kettle", brand: "Fellow", category: "Home & Living", price: 165, originalPrice: 165, stock: 55, rating: 4.8, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&q=80&w=800", description: "Precision pour spout and exact temperature control for perfect pour-over coffee." },
  { title: "Simplehuman Dual Compartment Trash Can", brand: "Simplehuman", category: "Home & Living", price: 199, originalPrice: 199, stock: 35, rating: 4.7, featured: false, bestseller: false, image: "https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?auto=format&fit=crop&q=80&w=800", description: "Neatly sort your trash and recyclables in this dual-bucket step can." },
  { title: "Bala Bangles", brand: "Bala", category: "Home & Living", price: 55, originalPrice: 55, stock: 120, rating: 4.6, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&q=80&w=800", description: "Wearable weights for your wrists and ankles to add constant but comfortable resistance." },
  { title: "Theragun Pro", brand: "Therabody", category: "Home & Living", price: 599, originalPrice: 599, stock: 30, rating: 4.8, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&q=80&w=800", description: "Powerful, commercial-grade percussive therapy device for deep muscle treatment." },
  { title: "Hatch Restore Smart Sleep Assistant", brand: "Hatch", category: "Home & Living", price: 129, originalPrice: 129, stock: 80, rating: 4.7, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&q=80&w=800", description: "Combine a sound machine, sunrise alarm, smart light, and meditation app." },

  // Beauty (15)
  { title: "Dior Sauvage Eau de Parfum", brand: "Dior", category: "Beauty", price: 145, originalPrice: 145, stock: 85, rating: 4.9, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=800", description: "A highly concentrated interpretation of Sauvage, melding extreme freshness with warm oriental tones." },
  { title: "Chanel Coco Mademoiselle", brand: "Chanel", category: "Beauty", price: 165, originalPrice: 165, stock: 70, rating: 4.9, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=800", description: "An irresistibly sexy, irrepressibly spirited oriental fragrance." },
  { title: "Maybelline Sky High Mascara", brand: "Maybelline", category: "Beauty", price: 12, originalPrice: 12, stock: 250, rating: 4.6, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&q=80&w=800", description: "Sensational length and volume mascara for limitless eyelash look." },
  { title: "CeraVe Hydrating Facial Cleanser", brand: "CeraVe", category: "Beauty", price: 15, originalPrice: 15, stock: 300, rating: 4.8, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&q=80&w=800", description: "Cleanses, hydrates, and helps restore the protective skin barrier." },
  { title: "Fenty Beauty Pro Filt'r Foundation", brand: "Fenty Beauty", category: "Beauty", price: 40, originalPrice: 40, stock: 150, rating: 4.7, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&q=80&w=800", description: "A soft matte, longwear foundation with buildable, medium to full coverage." },
  { title: "Olaplex No. 7 Bonding Oil", brand: "Olaplex", category: "Beauty", price: 30, originalPrice: 30, stock: 180, rating: 4.8, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&q=80&w=800", description: "A highly-concentrated, weightless reparative styling oil." },
  { title: "Paula's Choice 2% BHA Liquid Exfoliant", brand: "Paula's Choice", category: "Beauty", price: 34, originalPrice: 34, stock: 120, rating: 4.8, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&q=80&w=800", description: "A gentle leave-on exfoliant with salicylic acid that quickly unclogs pores." },
  { title: "Charlotte Tilbury Pillow Talk Lipstick", brand: "Charlotte Tilbury", category: "Beauty", price: 35, originalPrice: 35, stock: 100, rating: 4.8, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&q=80&w=800", description: "The iconic, universally flattering nude-pink lipstick." },
  { title: "NARS Radiant Creamy Concealer", brand: "NARS", category: "Beauty", price: 32, originalPrice: 32, stock: 140, rating: 4.7, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&q=80&w=800", description: "Award-winning, multi-purpose concealer with up to 16-hour wear." },
  { title: "La Mer Crème de la Mer", brand: "La Mer", category: "Beauty", price: 380, originalPrice: 380, stock: 20, rating: 4.9, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&q=80&w=800", description: "The luxurious moisturizer that started it all, with the renewing Miracle Broth." },
  { title: "Supergoop! Unseen Sunscreen SPF 40", brand: "Supergoop!", category: "Beauty", price: 38, originalPrice: 38, stock: 200, rating: 4.8, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&q=80&w=800", description: "The original, totally invisible, weightless, scentless sunscreen with SPF 40." },
  { title: "Glossier Boy Brow", brand: "Glossier", category: "Beauty", price: 18, originalPrice: 18, stock: 220, rating: 4.6, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&q=80&w=800", description: "A brushable, creamy wax that visibly thickens, shapes, and grooms brows into place." },
  { title: "Laneige Lip Sleeping Mask", brand: "Laneige", category: "Beauty", price: 24, originalPrice: 24, stock: 160, rating: 4.8, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&q=80&w=800", description: "A leave-on lip mask that delivers intense moisture and antioxidants while you sleep." },
  { title: "Estée Lauder Advanced Night Repair", brand: "Estée Lauder", category: "Beauty", price: 115, originalPrice: 115, stock: 75, rating: 4.8, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&q=80&w=800", description: "Deep- and fast-penetrating face serum reduces the look of multiple signs of aging." },
  { title: "Rare Beauty Soft Pinch Liquid Blush", brand: "Rare Beauty", category: "Beauty", price: 23, originalPrice: 23, stock: 190, rating: 4.9, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&q=80&w=800", description: "A weightless, long-lasting liquid blush that blends and builds beautifully." },

  // Sports (10)
  { title: "Wilson Evolution Indoor Basketball", brand: "Wilson", category: "Sports", price: 79, originalPrice: 79, stock: 100, rating: 4.9, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1519861531473-9200262188bf?auto=format&fit=crop&q=80&w=800", description: "The #1 indoor game basketball in America, featuring unmatched feel and durability." },
  { title: "Spalding NBA Official Game Ball", brand: "Spalding", category: "Sports", price: 169, originalPrice: 169, stock: 40, rating: 4.8, featured: false, bestseller: false, image: "https://images.unsplash.com/photo-1519861531473-9200262188bf?auto=format&fit=crop&q=80&w=800", description: "The official basketball of the NBA with full-grain leather cover." },
  { title: "YETI Hopper Flip 12 Soft Cooler", brand: "YETI", category: "Sports", price: 250, originalPrice: 250, stock: 60, rating: 4.8, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?auto=format&fit=crop&q=80&w=800", description: "100% leakproof, tough-as-nails, and keeps ice for days." },
  { title: "Bowflex SelectTech 552 Dumbbells", brand: "Bowflex", category: "Sports", price: 429, originalPrice: 429, stock: 35, rating: 4.9, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&q=80&w=800", description: "Adjustable dumbbells that replace 15 sets of weights." },
  { title: "Liforme Yoga Mat", brand: "Liforme", category: "Sports", price: 149, originalPrice: 149, stock: 75, rating: 4.9, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&q=80&w=800", description: "The ultimate yoga mat with alignment markers and incredible grip." },
  { title: "Hydro Flask 32 oz Wide Mouth", brand: "Hydro Flask", category: "Sports", price: 45, originalPrice: 45, stock: 150, rating: 4.8, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&q=80&w=800", description: "Double-wall vacuum insulation keeps drinks cold up to 24 hours." },
  { title: "Titleist Pro V1 Golf Balls", brand: "Titleist", category: "Sports", price: 55, originalPrice: 55, stock: 200, rating: 4.9, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1535139262971-c5184570fa6b?auto=format&fit=crop&q=80&w=800", description: "The most trusted golf ball in the game with total performance." },
  { title: "Babolat Pure Drive Tennis Racquet", brand: "Babolat", category: "Sports", price: 249, originalPrice: 249, stock: 45, rating: 4.8, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?auto=format&fit=crop&q=80&w=800", description: "The standard for power and versatility on the tennis court." },
  { title: "Fitbit Charge 6", brand: "Fitbit", category: "Sports", price: 159, originalPrice: 159, stock: 90, rating: 4.6, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&q=80&w=800", description: "Advanced fitness and health tracker with Google tools." },
  { title: "CamelBak M.U.L.E. Hydration Pack", brand: "CamelBak", category: "Sports", price: 115, originalPrice: 115, stock: 55, rating: 4.8, featured: false, bestseller: false, image: "https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?auto=format&fit=crop&q=80&w=800", description: "The iconic mountain biking hydration pack with 3L reservoir." },

  // Books (10)
  { title: "Atomic Habits", brand: "Penguin", category: "Books", price: 14, originalPrice: 27, stock: 250, rating: 4.9, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800", description: "An Easy & Proven Way to Build Good Habits & Break Bad Ones by James Clear." },
  { title: "Dune", brand: "Ace Books", category: "Books", price: 18, originalPrice: 18, stock: 150, rating: 4.8, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800", description: "Frank Herbert's classic masterpiece—a triumph of the imagination and one of the bestselling science fiction novels of all time." },
  { title: "Thinking, Fast and Slow", brand: "Farrar, Straus and Giroux", category: "Books", price: 16, originalPrice: 20, stock: 120, rating: 4.7, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800", description: "The renowned psychologist and winner of the Nobel Prize in Economics, Daniel Kahneman, takes us on a groundbreaking tour of the mind." },
  { title: "Sapiens: A Brief History of Humankind", brand: "Harper", category: "Books", price: 22, originalPrice: 25, stock: 180, rating: 4.8, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800", description: "Yuval Noah Harari's bold, wide-ranging, and provocative book explores who we are, how we got here, and where we're going." },
  { title: "The Midnight Library", brand: "Viking", category: "Books", price: 15, originalPrice: 26, stock: 140, rating: 4.6, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800", description: "A dazzling novel about all the choices that go into a life well lived, from the internationally bestselling author Matt Haig." },
  { title: "Project Hail Mary", brand: "Ballantine Books", category: "Books", price: 17, originalPrice: 28, stock: 130, rating: 4.9, featured: true, bestseller: true, image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800", description: "An interstellar tale of discovery and survival by Andy Weir, the author of The Martian." },
  { title: "The Creative Act: A Way of Being", brand: "Penguin Press", category: "Books", price: 20, originalPrice: 32, stock: 95, rating: 4.8, featured: true, bestseller: false, image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800", description: "From the legendary music producer Rick Rubin, a masterwork on the creative process." },
  { title: "Tomorrow, and Tomorrow, and Tomorrow", brand: "Knopf", category: "Books", price: 16, originalPrice: 28, stock: 110, rating: 4.7, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800", description: "A novel by Gabrielle Zevin that examines the multifarious nature of identity, disability, failure, and the redemptive possibilities in play." },
  { title: "Deep Work", brand: "Grand Central Publishing", category: "Books", price: 15, originalPrice: 30, stock: 160, rating: 4.7, featured: false, bestseller: false, image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800", description: "Rules for focused success in a distracted world by Cal Newport." },
  { title: "Meditations", brand: "Modern Library", category: "Books", price: 11, originalPrice: 11, stock: 200, rating: 4.8, featured: false, bestseller: true, image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800", description: "The timeless philosophical writings of Roman Emperor Marcus Aurelius." }
];

mongoose.connect(process.env.MONGO_URI, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
})
.then(async () => {
  console.log('Connected to MongoDB');
  
  // Clear existing products
  await Product.deleteMany({});
  console.log('Cleared existing products');
  
  // Insert new products
  await Product.insertMany(products);
  console.log(`Successfully seeded ${products.length} products`);
  
  process.exit();
})
.catch((err) => {
  console.error('Error seeding database:', err);
  process.exit(1);
});
